ALTER TABLE users
ADD COLUMN role VARCHAR(50) NOT NULL DEFAULT 'EMPLOYEE',
ADD COLUMN company_id UUID REFERENCES companies(id);

ALTER TABLE users
ADD CONSTRAINT chk_users_role
CHECK (role IN ('ADMIN', 'DEVELOPER', 'EMPLOYEE'));
