ALTER TABLE products
ADD COLUMN code VARCHAR(255),
ADD COLUMN company_id UUID REFERENCES companies(id),
ADD COLUMN "bikeModel" VARCHAR(255),
ADD COLUMN stock_quantity INTEGER;

ALTER TABLE products
ALTER COLUMN price TYPE NUMERIC(19,2) USING price::NUMERIC(19,2);

ALTER TABLE products
DROP COLUMN category;
